<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <ItemGroup>
    <ProjectReference Include="..\PointOfSale.Application\PointOfSale.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>false</ImplicitUsings>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

</Project>